export const NAVBAR_LOGO = [
  { src: '/images/image1.jpg', alt: 'Logo PT Yumenari Global Indonesia' },
  { src: '/images/image2.jpg', alt: 'Logo LPKS Yumenari Gakkou' },
]
export const FOOTER_LOGO = '/images/image1.jpg'

export const site = {
  brand: {
    name: 'YUMENARI GLOBAL',
    legalName: 'PT Yumenari Global Indonesia',
    tagline: 'Persiapkan Diri, Raih Peluang Global',
  },
  navigation: [
    { label: 'Tentang Kami', href: '#tentang-kami' },
    { label: 'Program', href: '#program' },
    { label: 'Artikel dan Informasi', href: '#artikel-informasi' },
    { label: 'Kerja Sama', href: '#kerja-sama' },
    { label: 'Kontak', href: '#kontak' },
  ],
  anchors: {
    home: '#beranda',
    about: '#tentang-kami',
    program: '#program',
    articles: '#artikel-informasi',
    partnership: '#kerja-sama',
    schedule: '#jadwal',
    activities: '#kegiatan',
    alumni: '#alumni',
    faq: '#faq',
    contact: '#kontak',
    registration: '#pendaftaran',
    studentData: '#data-siswa',
  },
  ui: {
    openMenu: 'Buka menu',
    closeMenu: 'Tutup menu',
    mainNavigation: 'Navigasi utama',
    signIn: 'Masuk',
    signUp: 'Daftar',
    registration: 'Pendaftaran',
    studentData: 'Data Siswa',
    registrationTitle: 'Formulir pendaftaran siswa',
    registrationDescription: 'Isi data diri untuk menyimpan pendaftaran pada akun Anda.',
    saveRegistration: 'Simpan data pendaftaran',
    updateRegistration: 'Perbarui data pendaftaran',
    savingRegistration: 'Menyimpan...',
    registrationSaved: 'Data pendaftaran tersimpan di akun Anda.',
    registrationError: 'Data belum tersimpan. Coba lagi.',
    registrationEmpty: 'Data siswa belum diisi.',
    registrationPrivacy: 'Data ini disimpan pada profil akun Clerk Anda dan hanya ditampilkan setelah Anda masuk.',
    studentFields: [
      { key: 'fullName', label: 'Nama lengkap' },
      { key: 'phone', label: 'Nomor telepon' },
      { key: 'birthDate', label: 'Tanggal lahir' },
      { key: 'gender', label: 'Jenis kelamin' },
      { key: 'address', label: 'Alamat domisili' },
      { key: 'education', label: 'Pendidikan terakhir' },
      { key: 'program', label: 'Program yang diminati' },
    ],
    fullName: 'Nama lengkap',
    phone: 'Nomor telepon',
    birthDate: 'Tanggal lahir',
    gender: 'Jenis kelamin',
    genderPlaceholder: 'Pilih jenis kelamin',
    genderOptions: ['Laki-laki', 'Perempuan'],
    address: 'Alamat domisili',
    education: 'Pendidikan terakhir',
    educationPlaceholder: 'Pilih pendidikan terakhir',
    educationOptions: ['SMP/sederajat', 'SMA/SMK/sederajat', 'Diploma', 'Sarjana', 'Lainnya'],
    japaneseProgram: 'Program yang diminati',
    japaneseProgramOptions: ['Bahasa Jepang dan kaiwa', 'Persiapan kerja Jepang', 'Persiapan JFT/JLPT', 'Persiapan interview dan budaya kerja', 'Program terkait SSW/Tokutei Ginou'],
    studentDataTitle: 'Data siswa',
    accountEmail: 'Email akun',
    noStudentData: 'Belum ada data pendaftaran. Isi formulir pendaftaran untuk memulai.',
    editRegistration: 'Ubah pendaftaran',
    partnershipTitle: 'Informasi kerja sama',
    partnershipPlaceholder: 'Informasi kerja sama akan ditampilkan setelah tersedia.',
    destinations: 'Tujuan program',
    focusHeading: 'Fokus persiapan',
    focusItems: ['Bahasa Jepang', 'Kaiwa', 'Interview', 'Budaya kerja'],
    japanPreparationLabel: 'PERSIAPAN KE JEPANG',
    imageIndex: '01 / 02',
    preparationStamp: 'GLOBAL PREPARATION',
    askProgram: 'Tanya program',
    askDirectly: 'Tanyakan langsung',
    backToTop: 'Kembali ke atas',
    logoPlaceholder: 'LOGO',
  },
  hero: {
    eyebrow: 'PERSIAPAN KERJA KE JEPANG',
    headline: 'Persiapkan Diri untuk Berkarier ke Jepang',
    subheadline:
      'Belajar bahasa, budaya kerja, dan keterampilan yang dibutuhkan untuk mempersiapkan diri menghadapi peluang kerja internasional.',
    primaryCta: 'Konsultasi Sekarang',
    secondaryCta: 'Jelajahi Program',
    image: {
      src: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1400&q=85',
      alt: 'Suasana jalan di Kyoto, Jepang',
      caption: 'Jepang',
      detail: 'Mulai dari bahasa, lanjut ke persiapan kerja.',
    },
    destinations: ['JEPANG'],
  },
  profile: {
    eyebrow: 'MENGENAL YUMENARI GLOBAL',
    title: 'Satu tempat untuk memulai persiapanmu.',
    description:
      'Yumenari Global adalah lembaga pelatihan kerja yang mempersiapkan peserta untuk bekerja dan mengikuti program ke Jepang.',
    note: 'Program dan ketersediaan dapat berubah. Detail terbaru dapat dikonfirmasi saat konsultasi.',
  },
  advantages: [
    {
      number: '01',
      title: 'Bahasa untuk komunikasi',
      description: 'Persiapan Bahasa Jepang dan kaiwa untuk membangun kesiapan komunikasi.',
      icon: 'languages',
    },
    {
      number: '02',
      title: 'Bekal menghadapi seleksi',
      description: 'Persiapan interview serta pengenalan JFT/JLPT.',
      icon: 'messages',
    },
    {
      number: '03',
      title: 'Mengenal budaya kerja',
      description: 'Belajar budaya dan etika kerja sebagai bagian dari persiapan.',
      icon: 'globe',
    },
  ],
  programs: {
    eyebrow: 'PILIH ARAH PERSIAPAN',
    title: 'Program sesuai tujuanmu.',
    description: 'Kenali pilihan pembelajaran untuk mempersiapkan diri mengikuti peluang program ke Jepang.',
    items: [
      {
        country: 'JEPANG',
        title: 'Persiapan Kerja Jepang',
        description: 'Persiapan bahasa, interview, budaya kerja, dan informasi program terkait SSW/Tokutei Ginou.',
        tags: ['Bahasa Jepang', 'Kaiwa', 'JFT / JLPT', 'SSW / Tokutei Ginou'],
        icon: 'japan',
      },
      {
        country: 'BAHASA & KOMUNIKASI',
        title: 'Bahasa Jepang dan Kaiwa',
        description: 'Latihan bahasa Jepang dan percakapan untuk membangun kesiapan komunikasi.',
        tags: ['Bahasa Jepang', 'Kaiwa', 'Percakapan'],
        icon: 'language',
      },
      {
        country: 'PERSIAPAN SELEKSI',
        title: 'Interview dan Budaya Kerja',
        description: 'Persiapan interview serta pengenalan budaya dan etika kerja.',
        tags: ['Interview', 'Budaya kerja', 'Etika kerja'],
        icon: 'interview',
      },
    ],
    note: 'Ketersediaan program, jadwal, dan persyaratan dapat dikonfirmasi melalui konsultasi.',
  },
  schedule: {
    eyebrow: 'JADWAL PROGRAM',
    title: 'Cari waktu yang paling sesuai.',
    description: 'Informasi jadwal dan pembukaan kelas akan diperbarui melalui konsultasi.',
    status: 'Jadwal terbaru',
    placeholder: '[Jadwal akan diinformasikan saat konsultasi]',
    cta: 'Tanyakan Jadwal',
  },
  activities: {
    eyebrow: 'SUASANA KEGIATAN',
    title: 'Belajar dan mempersiapkan langkah berikutnya.',
    description: 'Informasi kegiatan belajar Yumenari Global akan ditampilkan di sini.',
    placeholders: [
      'Foto kegiatan belajar bahasa',
      'Foto kegiatan persiapan interview',
      'Foto kegiatan pengenalan budaya kerja',
    ],
  },
  alumni: {
    eyebrow: 'INFORMASI PESERTA',
    title: 'Informasi untuk calon peserta.',
    description: 'Informasi peserta akan diperbarui saat tersedia.',
    placeholder: 'Informasi peserta akan ditampilkan di sini setelah tersedia.',
  },
  faqs: {
    eyebrow: 'PERTANYAAN UMUM',
    title: 'Sebelum mulai, cari tahu dulu.',
    items: [
      {
        question: 'Program apa saja yang tersedia di Yumenari Global?',
        answer:
          'Fokus persiapan mencakup Bahasa Jepang, kaiwa, persiapan kerja dan interview, budaya serta etika kerja, JFT/JLPT, dan informasi program terkait SSW/Tokutei Ginou. Ketersediaan setiap program dapat dikonfirmasi melalui WhatsApp.',
      },
      {
        question: 'Apakah setelah mengikuti program saya pasti bekerja atau berangkat?',
        answer:
          'Tidak ada jaminan bekerja atau berangkat. Program berfokus pada persiapan; hasil seleksi dan kesempatan kerja bergantung pada proses serta ketentuan yang berlaku.',
      },
      {
        question: 'Berapa biaya dan berapa lama program berlangsung?',
        answer:
          'Informasi biaya dan durasi belum tersedia di halaman ini. Silakan tanyakan detail terbaru melalui konsultasi WhatsApp.',
      },
      {
        question: 'Apa persyaratan untuk mendaftar?',
        answer:
          'Persyaratan dapat berbeda menurut program dan belum dicantumkan di sini. Hubungi kami melalui WhatsApp untuk memastikan persyaratan program yang diminati.',
      },
      {
        question: 'Bagaimana cara mengetahui jadwal kelas?',
        answer:
          'Jadwal terbaru dapat ditanyakan melalui konsultasi WhatsApp. Informasi jadwal akan diperbarui di halaman ini saat tersedia.',
      },
    ],
  },
  contact: {
    eyebrow: 'MULAI DENGAN KONSULTASI',
    title: 'Langkah pertama dimulai dari percakapan.',
    description:
      'Ceritakan tujuanmu. Tim Yumenari Global dapat membantu memberi informasi program yang tersedia.',
    cta: 'Konsultasi WhatsApp',
    whatsappUrl: '',
    whatsappPlaceholder: '[Nomor WhatsApp]',
    address: '[Alamat akan diinformasikan]',
    email: '[Email akan diinformasikan]',
  },
  partnership: {
    title: 'Informasi kerja sama',
    description: 'Informasi kerja sama akan ditampilkan setelah tersedia.',
  },
  footer: {
    note: 'Informasi program dapat berubah. Konfirmasikan ketersediaan dan detail melalui konsultasi.',
    copyright: 'Hak cipta dilindungi.',
  },
} as const